source "https://rubygems.org"

gem 'json'
gem 'colorize'
gem 'sinatra'
gem 'httparty'
gem 'activerecord', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'rake'
gem 'require_all'
gem 'sqlite3'
gem 'thin'
gem 'shotgun'
gem 'pry'
gem 'tty-prompt'
